export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TITLE = "SET_CURRENT_TITLE";
export const ADDELEMENT = "ADDELEMENT";
export const CHANGEQUESTION = "CHANGEQUESTION";
export const SET_ELEMENTS = "SET_ELEMENTS";